// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsBettingTracker.Data;

#nullable disable

namespace SportsBettingTracker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250530160410_BetTypeConfigAndLeagueOrder")]
    partial class BetTypeConfigAndLeagueOrder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("SportsBettingTracker.Models.Bet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AmountWonLost")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("BetDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("BetSelection")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("BetType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Match")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Odds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Result")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SportLeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Stake")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("SportLeagueId");

                    b.ToTable("Bets");
                });

            modelBuilder.Entity("SportsBettingTracker.Models.BetTypeConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BetType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BetTypeConfigurations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BetType = 0,
                            Description = "Bet on which team wins the game outright",
                            DisplayName = "Moneyline",
                            DisplayOrder = 1,
                            IsActive = true
                        },
                        new
                        {
                            Id = 2,
                            BetType = 1,
                            Description = "Bet on the margin of victory",
                            DisplayName = "Spread",
                            DisplayOrder = 2,
                            IsActive = true
                        },
                        new
                        {
                            Id = 3,
                            BetType = 2,
                            Description = "Bet on the total combined score",
                            DisplayName = "Over/Under",
                            DisplayOrder = 3,
                            IsActive = true
                        },
                        new
                        {
                            Id = 4,
                            BetType = 3,
                            Description = "Bet on specific events within the game",
                            DisplayName = "Prop Bet",
                            DisplayOrder = 4,
                            IsActive = true
                        },
                        new
                        {
                            Id = 5,
                            BetType = 4,
                            Description = "Multiple bets combined into one wager",
                            DisplayName = "Parlay",
                            DisplayOrder = 5,
                            IsActive = true
                        },
                        new
                        {
                            Id = 6,
                            BetType = 5,
                            Description = "Bet on long-term outcomes like championship winners",
                            DisplayName = "Future",
                            DisplayOrder = 6,
                            IsActive = true
                        },
                        new
                        {
                            Id = 7,
                            BetType = 6,
                            Description = "Other bet types",
                            DisplayName = "Other",
                            DisplayOrder = 7,
                            IsActive = true
                        });
                });

            modelBuilder.Entity("SportsBettingTracker.Models.SportLeague", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SportLeagues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "National Football League",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "NFL"
                        },
                        new
                        {
                            Id = 2,
                            Description = "National Basketball Association",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "NBA"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Major League Baseball",
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "MLB"
                        },
                        new
                        {
                            Id = 4,
                            Description = "National Hockey League",
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "NHL"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Ultimate Fighting Championship",
                            DisplayOrder = 5,
                            IsActive = true,
                            Name = "UFC"
                        },
                        new
                        {
                            Id = 6,
                            Description = "English Premier League",
                            DisplayOrder = 6,
                            IsActive = true,
                            Name = "Soccer - Premier League"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Major League Soccer",
                            DisplayOrder = 7,
                            IsActive = true,
                            Name = "Soccer - MLS"
                        });
                });

            modelBuilder.Entity("SportsBettingTracker.Models.Bet", b =>
                {
                    b.HasOne("SportsBettingTracker.Models.SportLeague", "SportLeague")
                        .WithMany("Bets")
                        .HasForeignKey("SportLeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SportLeague");
                });

            modelBuilder.Entity("SportsBettingTracker.Models.SportLeague", b =>
                {
                    b.Navigation("Bets");
                });
#pragma warning restore 612, 618
        }
    }
}
